//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Participant
    {
        public int ParticipantId { get; set; }
        public int EventId { get; set; }
        public int ChildrenId { get; set; }
        [Display(Name = "Lane")]
        public int Lane { get; set; }
        [Display(Name = "Time")]
        public System.TimeSpan Time { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual Event Event { get; set; }
    }
}
